### PR TITLE
Fix baseurl for RHEL and Suse

### LINKED ISSUE #36: Chrome cron script overrides HTTPS repository URL configuration on Red Hat variants
Even if the initial Puppet run configures the the Chrome yum repository URL to use HTTPS, this gets silently overwritten back to standard HTTP by the `/etc/cron.daily/google-chrome` script.

On Debian / Ubuntu, the cron script has a `REPOCONFIGREGEX`  variable which checks for `https`. The Red Hat flavour has no such check.

### PR DESCRIPTION
**Pull request by treydock**
Fixes #36

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Thanks!

**Comment by jamesnetherton** [comment]
@treydock I just remebered we tried to do this before but hit some issues:

https://github.com/jamesnetherton/puppet-google-chrome/issues/36#issue-562011653

https://bugs.chromium.org/p/chromium/issues/detail?id=1050459

Do you know if the problem still exists?

**Comment by treydock** [comment]
That issue is solved, it looks like the default behavior for google-chrome is to use HTTPS, they have this in `/etc/cron.daily/google-chrome`:

```
REPOCONFIG="https://dl.google.com/linux/chrome/rpm/stable"
```

So without this pull request, the Puppet module would set HTTP but Google's cron job would want HTTPS.  So this pull request makes the Puppet module do what Google Chrome's cron job is expecting.

**Comment by treydock** [comment]
Would it be possible to get a new tag and Forge release that includes this pull request?

**Pull request merged**
