### PR TITLE
Can we use https in repo_base_url ?

### PR DESCRIPTION
**Pull request by meskaya**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
It should be ok. Most of the integration tests seem to have passed.

Please can you also update the `baseurl` param references in `spec/classes/chrome_browser_spec.rb` to use https.

**Comment by jamesnetherton** [comment]
Sorry - can you also tweak the `location` param to https in the spec. 

Should be good to merge after that.

**Comment by jamesnetherton** [comment]
I'll try to make a new release over the weekend.

**Comment by jamesnetherton** [comment]
@meskaya I think I'm going to revert back to HTTP for Red Hat / CentOS / SUSE because of https://github.com/jamesnetherton/puppet-google-chrome/issues/36.

I can keep HTTPS  for Debian / Ubuntu.

Let me know if this is a problem for you.

**Comment by meskaya** [comment]
@jamesnetherton Ok no problem we don't really have the choice (I completely missed the daily cronjob on RedHat based OS).
I did a bug report from Google Chrome (first time I am doing this) to get the same regexp check on Redhat OS based.

**Comment by meskaya** [comment]
@jamesnetherton is it possible to do a new release with https only on Ubuntu ?

**Pull request merged**
